#!/bin/sh

PATH=/bin:/sbin:/usr/bin:/usr/sbin

get_ipv4_address() {
	if command -v ip >/dev/null 2>&1; then
		ip -4 -o addr show dev eth0 scope global 2>/dev/null \
			| sed -n 's/.* inet \([0-9.]*\)\/.*$/\1/p;q'
		return
	fi

	if command -v ifconfig >/dev/null 2>&1; then
		ifconfig eth0 2>/dev/null \
			| sed -n 's/.*inet addr:\([0-9.]*\).*/\1/p; s/.*inet \([0-9.]*\).*/\1/p' \
			| sed -n '1p'
	fi
}

ip_address=""
tries=30

while [ "$tries" -gt 0 ]; do
	ip_address="$(get_ipv4_address)"
	if [ -n "$ip_address" ]; then
		break
	fi
	tries=$((tries - 1))
	sleep 1
done

if [ -z "$ip_address" ]; then
	ip_address="unavailable"
fi

cat > /etc/motd <<'EOF'
   _____                  __                         _       __ 
  / ___/____  ___  ____ _/ /_____  _________  ____  (_)___  / /_
  \__ \/ __ \/ _ \/ __ `/ //_/ _ \/ ___/ __ \/ __ \/ / __ \/ __/
 ___/ / /_/ /  __/ /_/ / ,< /  __/ /  / /_/ / /_/ / / / / / /_  
/____/ .___/\___/\__,_/_/|_|\___/_/  / .___/\____/_/_/ /_/\__/   
    /_/                             /_/                          

Open-Source and modern firmware for the legacy Control4 Speakerpoint
Not endorsed or affiliated by Control4
View the web configuration at http://__IP_ADDRESS__

EOF

sed "s/__IP_ADDRESS__/$ip_address/" /etc/motd > /tmp/.motd && mv /tmp/.motd /etc/motd

exit 0