#!/bin/sh

case "$1" in
	start)
		printf 'Starting example-daemon: '
		start-stop-daemon -S -q -m -b -p /var/run/example-daemon.pid \
			-x /usr/bin/example-daemon
		echo "OK"
		;;
	stop)
		printf 'Stopping example-daemon: '
		start-stop-daemon -K -q -p /var/run/example-daemon.pid
		echo "OK"
		;;
	restart|reload)
		"$0" stop
		"$0" start
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
		;;
esac

exit 0
